module.exports =
  michael:
    first_name: "Michael"
    last_name: "Richards"
    short_bio: "Ruby/JavaScript developer. Author of Rivets.js."
    email: "mike22e@gmail.com"
    twitter: "https://github.com/mikeric"
    github: "http://github.com/wmdmark"
    website: ""
  mark:
    first_name: "Mark"
    last_name: "Johnson"
    short_bio: "Web designer, developer and teacher. Co-founder of Pathwright"
    email: "wmdmark@gmail.com"
    twitter: "http://twitter.com/wmdmark"
    github: "http://github.com/wmdmark"
    website: "http://pathwright.com"
  mason:
    first_name: "Mason"
    last_name: "Stewart"
    short_bio: "Frontender, JavaScripter, & Lisper"
    email: "mason@theironyard.com"
    twitter: "http://twitter.com/masondesu"
    github: "https://github.com/masondesu"
    website: ""
